// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pool/api/pool.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node_Kind int32

const (
	Node_UNKNOWN Node_Kind = 0
	Node_GETH    Node_Kind = 1
	Node_PARITY  Node_Kind = 2
)

var Node_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "GETH",
	2: "PARITY",
}
var Node_Kind_value = map[string]int32{
	"UNKNOWN": 0,
	"GETH":    1,
	"PARITY":  2,
}

func (x Node_Kind) String() string {
	return proto.EnumName(Node_Kind_name, int32(x))
}
func (Node_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{1, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Node struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uri                  string    `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Kind                 Node_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=vipnode.pool.api.Node_Kind" json:"kind,omitempty"`
	Version              string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Host                 bool      `protobuf:"varint,5,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{1}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Node) GetKind() Node_Kind {
	if m != nil {
		return m.Kind
	}
	return Node_UNKNOWN
}

func (m *Node) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Node) GetHost() bool {
	if m != nil {
		return m.Host
	}
	return false
}

type RegisterRequest struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	NodeSig              string   `protobuf:"bytes,3,opt,name=node_sig,json=nodeSig,proto3" json:"node_sig,omitempty"`
	Wallet               string   `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	WalletAuthorization  string   `protobuf:"bytes,5,opt,name=wallet_authorization,json=walletAuthorization,proto3" json:"wallet_authorization,omitempty"`
	IsHost               bool     `protobuf:"varint,6,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{2}
}
func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(dst, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *RegisterRequest) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *RegisterRequest) GetNodeSig() string {
	if m != nil {
		return m.NodeSig
	}
	return ""
}

func (m *RegisterRequest) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *RegisterRequest) GetWalletAuthorization() string {
	if m != nil {
		return m.WalletAuthorization
	}
	return ""
}

func (m *RegisterRequest) GetIsHost() bool {
	if m != nil {
		return m.IsHost
	}
	return false
}

type UpdateResponse struct {
	Balance              *Balance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	InvalidPeers         []string `protobuf:"bytes,2,rep,name=invalid_peers,json=invalidPeers,proto3" json:"invalid_peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{3}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *UpdateResponse) GetInvalidPeers() []string {
	if m != nil {
		return m.InvalidPeers
	}
	return nil
}

type UpdateRequest struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{4}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type Balance struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Credit               int32    `protobuf:"varint,2,opt,name=credit,proto3" json:"credit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{5}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (dst *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(dst, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Balance) GetCredit() int32 {
	if m != nil {
		return m.Credit
	}
	return 0
}

type HostRequest struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	NodeURI              string   `protobuf:"bytes,2,opt,name=nodeURI,proto3" json:"nodeURI,omitempty"`
	Payout               string   `protobuf:"bytes,3,opt,name=payout,proto3" json:"payout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostRequest) Reset()         { *m = HostRequest{} }
func (m *HostRequest) String() string { return proto.CompactTextString(m) }
func (*HostRequest) ProtoMessage()    {}
func (*HostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{6}
}
func (m *HostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostRequest.Unmarshal(m, b)
}
func (m *HostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostRequest.Marshal(b, m, deterministic)
}
func (dst *HostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostRequest.Merge(dst, src)
}
func (m *HostRequest) XXX_Size() int {
	return xxx_messageInfo_HostRequest.Size(m)
}
func (m *HostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HostRequest proto.InternalMessageInfo

func (m *HostRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *HostRequest) GetNodeURI() string {
	if m != nil {
		return m.NodeURI
	}
	return ""
}

func (m *HostRequest) GetPayout() string {
	if m != nil {
		return m.Payout
	}
	return ""
}

type HostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostResponse) Reset()         { *m = HostResponse{} }
func (m *HostResponse) String() string { return proto.CompactTextString(m) }
func (*HostResponse) ProtoMessage()    {}
func (*HostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{7}
}
func (m *HostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostResponse.Unmarshal(m, b)
}
func (m *HostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostResponse.Marshal(b, m, deterministic)
}
func (dst *HostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostResponse.Merge(dst, src)
}
func (m *HostResponse) XXX_Size() int {
	return xxx_messageInfo_HostResponse.Size(m)
}
func (m *HostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HostResponse proto.InternalMessageInfo

type ConnectRequest struct {
	ClientVersion        string   `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{8}
}
func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(dst, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *ConnectRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ConnectResponse struct {
	PoolVersion          string   `protobuf:"bytes,1,opt,name=pool_version,json=poolVersion,proto3" json:"pool_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pool_c9b55d2b4fccf415, []int{9}
}
func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(dst, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetPoolVersion() string {
	if m != nil {
		return m.PoolVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "vipnode.pool.api.Empty")
	proto.RegisterType((*Node)(nil), "vipnode.pool.api.Node")
	proto.RegisterType((*RegisterRequest)(nil), "vipnode.pool.api.RegisterRequest")
	proto.RegisterType((*UpdateResponse)(nil), "vipnode.pool.api.UpdateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "vipnode.pool.api.UpdateRequest")
	proto.RegisterType((*Balance)(nil), "vipnode.pool.api.Balance")
	proto.RegisterType((*HostRequest)(nil), "vipnode.pool.api.HostRequest")
	proto.RegisterType((*HostResponse)(nil), "vipnode.pool.api.HostResponse")
	proto.RegisterType((*ConnectRequest)(nil), "vipnode.pool.api.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "vipnode.pool.api.ConnectResponse")
	proto.RegisterEnum("vipnode.pool.api.Node_Kind", Node_Kind_name, Node_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoolClient is the client API for Pool service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoolClient interface {
	// Register the node with a desired wallet.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Balance, error)
	// Host subscribes a host to receive vipnode_whitelist instructions.
	Host(ctx context.Context, opts ...grpc.CallOption) (Pool_HostClient, error)
	// Connect requests for available hosts to connect to as a client.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Disconnect stops tracking the connection and billing, will prompt a
	// disconnect from both ends.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Update is a keep-alive for sharing the node's peering info. It returns
	// the current balance for the node.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Withdraw prompts a request to settle the node's balance.
	Withdraw(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type poolClient struct {
	cc *grpc.ClientConn
}

func NewPoolClient(cc *grpc.ClientConn) PoolClient {
	return &poolClient{cc}
}

func (c *poolClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := c.cc.Invoke(ctx, "/vipnode.pool.api.Pool/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolClient) Host(ctx context.Context, opts ...grpc.CallOption) (Pool_HostClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pool_serviceDesc.Streams[0], "/vipnode.pool.api.Pool/Host", opts...)
	if err != nil {
		return nil, err
	}
	x := &poolHostClient{stream}
	return x, nil
}

type Pool_HostClient interface {
	Send(*HostRequest) error
	Recv() (*HostResponse, error)
	grpc.ClientStream
}

type poolHostClient struct {
	grpc.ClientStream
}

func (x *poolHostClient) Send(m *HostRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *poolHostClient) Recv() (*HostResponse, error) {
	m := new(HostResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *poolClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/vipnode.pool.api.Pool/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/vipnode.pool.api.Pool/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/vipnode.pool.api.Pool/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolClient) Withdraw(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/vipnode.pool.api.Pool/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServer is the server API for Pool service.
type PoolServer interface {
	// Register the node with a desired wallet.
	Register(context.Context, *RegisterRequest) (*Balance, error)
	// Host subscribes a host to receive vipnode_whitelist instructions.
	Host(Pool_HostServer) error
	// Connect requests for available hosts to connect to as a client.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Disconnect stops tracking the connection and billing, will prompt a
	// disconnect from both ends.
	Disconnect(context.Context, *Empty) (*Empty, error)
	// Update is a keep-alive for sharing the node's peering info. It returns
	// the current balance for the node.
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// Withdraw prompts a request to settle the node's balance.
	Withdraw(context.Context, *Empty) (*Empty, error)
}

func RegisterPoolServer(s *grpc.Server, srv PoolServer) {
	s.RegisterService(&_Pool_serviceDesc, srv)
}

func _Pool_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vipnode.pool.api.Pool/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pool_Host_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PoolServer).Host(&poolHostServer{stream})
}

type Pool_HostServer interface {
	Send(*HostResponse) error
	Recv() (*HostRequest, error)
	grpc.ServerStream
}

type poolHostServer struct {
	grpc.ServerStream
}

func (x *poolHostServer) Send(m *HostResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *poolHostServer) Recv() (*HostRequest, error) {
	m := new(HostRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Pool_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vipnode.pool.api.Pool/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pool_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vipnode.pool.api.Pool/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pool_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vipnode.pool.api.Pool/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pool_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vipnode.pool.api.Pool/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServer).Withdraw(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pool_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vipnode.pool.api.Pool",
	HandlerType: (*PoolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Pool_Register_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Pool_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Pool_Disconnect_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Pool_Update_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _Pool_Withdraw_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Host",
			Handler:       _Pool_Host_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pool/api/pool.proto",
}

func init() { proto.RegisterFile("pool/api/pool.proto", fileDescriptor_pool_c9b55d2b4fccf415) }

var fileDescriptor_pool_c9b55d2b4fccf415 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x6f, 0x4f, 0x13, 0x4f,
	0x10, 0xee, 0xb5, 0x77, 0xbd, 0x32, 0x85, 0xd2, 0x0c, 0x04, 0x8e, 0xfe, 0xf2, 0xd3, 0x72, 0x86,
	0xa4, 0xfa, 0xa2, 0x28, 0xf8, 0xce, 0xc4, 0x08, 0x4a, 0x04, 0x89, 0xb5, 0x59, 0x40, 0xa2, 0x6f,
	0x9a, 0xe5, 0x6e, 0x03, 0xab, 0xe7, 0xed, 0x79, 0xb7, 0x85, 0xe0, 0xc7, 0xf2, 0x23, 0xf8, 0x11,
	0xfc, 0x44, 0x66, 0xff, 0x5c, 0x03, 0xd4, 0x6a, 0xe2, 0xbb, 0x7d, 0x66, 0x9e, 0x9d, 0x99, 0x67,
	0xf6, 0xc9, 0xc2, 0x52, 0x26, 0x44, 0xb2, 0x49, 0x33, 0xbe, 0xa9, 0x0e, 0xfd, 0x2c, 0x17, 0x52,
	0x60, 0xfb, 0x92, 0x67, 0xa9, 0x88, 0x59, 0x5f, 0xc7, 0x68, 0xc6, 0x43, 0x1f, 0xbc, 0xbd, 0x2f,
	0x99, 0xbc, 0x0e, 0xbf, 0x3b, 0xe0, 0x0e, 0x44, 0xcc, 0xb0, 0x05, 0x55, 0x1e, 0x07, 0x4e, 0xd7,
	0xe9, 0xcd, 0x91, 0x2a, 0x8f, 0xb1, 0x0d, 0xb5, 0x71, 0xce, 0x83, 0xaa, 0x0e, 0xa8, 0x23, 0x6e,
	0x82, 0xfb, 0x99, 0xa7, 0x71, 0x50, 0xeb, 0x3a, 0xbd, 0xd6, 0xd6, 0x7f, 0xfd, 0xbb, 0x45, 0xfb,
	0xaa, 0x4e, 0xff, 0x90, 0xa7, 0x31, 0xd1, 0x44, 0x0c, 0xc0, 0xbf, 0x64, 0x79, 0xc1, 0x45, 0x1a,
	0xb8, 0xba, 0x4c, 0x09, 0x11, 0xc1, 0xbd, 0x10, 0x85, 0x0c, 0xbc, 0xae, 0xd3, 0x6b, 0x10, 0x7d,
	0x0e, 0x1f, 0x82, 0xab, 0xee, 0x62, 0x13, 0xfc, 0x93, 0xc1, 0xe1, 0xe0, 0xdd, 0xe9, 0xa0, 0x5d,
	0xc1, 0x06, 0xb8, 0xaf, 0xf7, 0x8e, 0xf7, 0xdb, 0x0e, 0x02, 0xd4, 0x87, 0x3b, 0xe4, 0xe0, 0xf8,
	0x43, 0xbb, 0x1a, 0xfe, 0x74, 0x60, 0x91, 0xb0, 0x73, 0x5e, 0x48, 0x96, 0x13, 0xf6, 0x75, 0xcc,
	0x0a, 0x89, 0x8f, 0xc0, 0x55, 0xd3, 0x68, 0x05, 0xcd, 0xad, 0x95, 0xdf, 0x4f, 0x47, 0x34, 0x07,
	0x97, 0xc1, 0x4b, 0x45, 0x1a, 0x31, 0xad, 0xae, 0x46, 0x0c, 0xc0, 0x35, 0x68, 0xa8, 0xec, 0xa8,
	0xe0, 0xe7, 0x5a, 0xe3, 0x1c, 0xf1, 0x15, 0x3e, 0xe2, 0xe7, 0xb8, 0x02, 0xf5, 0x2b, 0x9a, 0x24,
	0x4c, 0x5a, 0x21, 0x16, 0xe1, 0x13, 0x58, 0x36, 0xa7, 0x11, 0x1d, 0xcb, 0x0b, 0x91, 0xf3, 0x6f,
	0x54, 0x2a, 0xb9, 0x9e, 0x66, 0x2d, 0x99, 0xdc, 0xce, 0xcd, 0x14, 0xae, 0x82, 0xcf, 0x8b, 0x91,
	0x56, 0x5f, 0xd7, 0xea, 0xeb, 0xbc, 0xd8, 0x57, 0xfa, 0x3f, 0x41, 0xeb, 0x24, 0x8b, 0xa9, 0x64,
	0x84, 0x15, 0x99, 0x48, 0x0b, 0x86, 0xdb, 0xe0, 0x9f, 0xd1, 0x84, 0xaa, 0x41, 0x8d, 0xaa, 0xb5,
	0x69, 0x55, 0xbb, 0x86, 0x40, 0x4a, 0x26, 0x3e, 0x80, 0x05, 0x9e, 0x5e, 0xd2, 0x84, 0xc7, 0xa3,
	0x8c, 0xb1, 0xbc, 0x08, 0xaa, 0xdd, 0x5a, 0x6f, 0x8e, 0xcc, 0xdb, 0xe0, 0x50, 0xc5, 0xc2, 0x0d,
	0x58, 0x28, 0x7b, 0x99, 0xed, 0x2d, 0x83, 0x67, 0xd8, 0x8e, 0x66, 0x1b, 0x10, 0x3e, 0x03, 0xdf,
	0xd6, 0x57, 0x6f, 0x49, 0xa3, 0x48, 0x8c, 0x53, 0x69, 0x3d, 0x52, 0x42, 0xb5, 0x9b, 0x28, 0x67,
	0x31, 0x97, 0x7a, 0x9b, 0x1e, 0xb1, 0x28, 0x3c, 0x82, 0xa6, 0xd2, 0x55, 0x76, 0x40, 0xeb, 0x1e,
	0x73, 0x7b, 0x62, 0x10, 0xa5, 0xe6, 0x84, 0x1c, 0x58, 0x9f, 0x95, 0x50, 0x15, 0xcd, 0xe8, 0xb5,
	0x18, 0x4b, 0xfb, 0x12, 0x16, 0x85, 0x2d, 0x98, 0x37, 0x45, 0xcd, 0x8a, 0xc2, 0x08, 0x5a, 0x2f,
	0x45, 0x9a, 0xb2, 0x68, 0xd2, 0x67, 0x03, 0x5a, 0x51, 0xc2, 0x59, 0x2a, 0x47, 0xa5, 0xf7, 0x4c,
	0xc7, 0x05, 0x13, 0x7d, 0x6f, 0x1d, 0x58, 0xda, 0xa5, 0xfa, 0x77, 0xbb, 0x84, 0x4f, 0x61, 0x71,
	0xd2, 0xc4, 0x3e, 0xcd, 0x3a, 0xcc, 0x2b, 0xe6, 0x9d, 0x1e, 0x4d, 0x15, 0xb3, 0x1d, 0xb6, 0x7e,
	0xd4, 0xc0, 0x1d, 0x0a, 0x91, 0xe0, 0x1b, 0x68, 0x94, 0x66, 0xc5, 0xf5, 0xe9, 0x46, 0x77, 0x8c,
	0xdc, 0x99, 0xfd, 0xc8, 0x61, 0x05, 0x0f, 0xc1, 0x55, 0xfa, 0xf1, 0xff, 0x69, 0xd2, 0x8d, 0x65,
	0x77, 0xee, 0xcd, 0x4a, 0xdb, 0xb5, 0x55, 0x7a, 0xce, 0x63, 0x07, 0x87, 0xe0, 0x5b, 0x5d, 0xd8,
	0x9d, 0xbe, 0x70, 0x7b, 0xaf, 0x9d, 0xf5, 0x3f, 0x30, 0xca, 0xaa, 0xf8, 0x02, 0xe0, 0x15, 0x2f,
	0x22, 0x5b, 0x74, 0x75, 0xfa, 0x8a, 0xfe, 0x74, 0x3a, 0xb3, 0x12, 0x61, 0x05, 0xdf, 0x42, 0xdd,
	0x38, 0x13, 0xef, 0x4f, 0x93, 0x6e, 0x79, 0xb6, 0xd3, 0x9d, 0x4d, 0x98, 0x0c, 0xf4, 0x1c, 0x1a,
	0xa7, 0x5c, 0x5e, 0xc4, 0x39, 0xbd, 0xfa, 0x97, 0x71, 0x76, 0xbd, 0x8f, 0x35, 0x9a, 0xf1, 0xb3,
	0xba, 0xfe, 0x47, 0xb7, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x40, 0xa1, 0x50, 0x5e, 0x05,
	0x00, 0x00,
}
